version: 2.1

jobs:
  build:
    docker:
      - image: python:3.7.9

    # working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Run Unit Tests
          command: |
            pip install pytest=6.2.1
            pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
